name: 'Update Agreena wiki'
description: 'This action updates Agreena wiki repository with changes made in base repository'
inputs:
  path:  
    description: 'Location of wiki directory'
    required: true
    default: 'wiki'
  token:
    description: 'Github token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "18"
        cache: "npm"
        registry-url: "https://npm.pkg.github.com"
        scope: "@agreena-aps"
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
    - run: sh ${{ github.action_path }}/update-wiki.sh 
      shell: bash
      env:       
        WIKI_DIR: ${{ inputs.path }}
        GH_TOKEN: ${{ inputs.token }}
branding:
  icon: book-open
  color: white 
